spring:
#  profiles:
#    active: ${active-profile:dev}
  applicaton:
    name: scalable-web
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    # H2 in local file system allowing other simultaneous connections
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

server:
  port: 9000
  # The error message and any binding errors are no longer included in the default error page by default.
  # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content
  error:
    include-message: always


#---
#profiles: prod
#  datasource:
#    url: ${datasource-url}
#    username: ${datasource-username}
#    password: ${datasource-password}

#---
#spring:
#  profiles: dev
#    jpa:
#      hibernate:
#        ddl-auto: create
#    datasource:
#      # H2 in local file system allowing other simultaneous connections
#      url: jdbc:h2:~/test;AUTO_SERVER=TRUE
#      driver-class-name: org.h2.Driver
#      username: sa
#      password: password
#  h2:
#    console:
#      enabled: true
